### ISSUE TITLE
Sensitivity to certain filenames

### ISSUE THREAD

**Issue by God-damnit-all** [Ehco1996/clash-speed#1]
`speedtest-clash --config proxylist-http.yaml` returns the error: `Get "proxylist-http.yaml": unsupported protocol scheme ""`

I tried surrounding the filename in quotes, but that didn't make a difference. Renaming the file and changing the command accordingly fixes the issue.

I'm on Windows 10 22H2 in case that's relevant.

**Comment by Ehco1996** [comment]
@ImportTaste  sorry for late reply


the correct file format is like this https://github.com/Ehco1996/speedtest-clash/blob/master/test/proxies.yaml

----

oh, i thinks this is a bug 😭
the default beheavior is trying get file through http if file name contains `http`
https://github.com/Ehco1996/speedtest-clash/blob/b8f5ffa4cc1fc8c92762ecef52a747e97ed7022d/pkg/clash/config.go#L49

**Comment by Ehco1996** [comment]
this should fixed by  https://github.com/Ehco1996/speedtest-clash/commit/92ab7570b18c8f42b067913413e9eae9150ab39c

please have a try

**Comment by God-damnit-all** [comment]
> this should fixed by [92ab757](https://github.com/Ehco1996/speedtest-clash/commit/92ab7570b18c8f42b067913413e9eae9150ab39c)
> 
> please have a try

Hm, I'm not sure how.

`>go install github.com/Ehco1996/speedtest-clash@latest`
```
go: downloading github.com/Ehco1996/speedtest-clash v0.0.0-20221009012859-92ab7570b18c
go: github.com/Ehco1996/speedtest-clash@latest: module github.com/Ehco1996/speedtest-clash@latest found (v0.0.0-20221009012859-92ab7570b18c), but does not contain package github.com/Ehco1996/speedtest-clash
```
I've never had to compile a Go repo any other way before.

**Comment by Ehco1996** [comment]
trying this
```
# install from github
go install github.com/Ehco1996/speedtest-clash/cmd@latest

# find the binary path
❯ go env | grep PATH
GOPATH="/Users/ehco/.gvm/pkgsets/system/global"

❯ ls /Users/ehco/.gvm/pkgsets/system/global/bin
cmd       gomobile  gotestsum retool


# cmd is the `speedtest-clash`binary

❯ /Users/ehco/.gvm/pkgsets/system/global/bin/cmd -h
use speedtest-clash to test your proxy server speed over www.speedtest.net

Usage:
  speedtest-clash [flags]

Flags:
      --concurrency int     tcp concurrency, note that more concurrency will use more traffic (default 1)
      --config string       clash config file path (also support download from http such as your clash subscribe link)
      --debug               enable debug log file
      --duration duration   time duration for speed test (default 3s)
  -h, --help                help for speedtest-clash
```

**Comment by God-damnit-all** [comment]
Ah, thank you. The fix works. Not sure why the binary it compiles is a good 5MB larger than the 0.1 binary though.

**Comment by Ehco1996** [comment]
> Ah, thank you. The fix works. Not sure why the binary it compiles is a good 5MB larger than the 0.1 binary though.

nice, 
> Not sure why the binary it compiles is a good 5MB larger than the 0.1 binary though.

this is because CI use upx to zip binary size see [here](https://github.com/Ehco1996/speedtest-clash/blob/92ab7570b18c8f42b067913413e9eae9150ab39c/.goreleaser.yml#L24)
